# Generated by Django 5.2.4 on 2025-07-16 12:58

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_total_amount"),
        ("payments", "0002_paymentrefund_payment_payment_method_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Server-calculated payment amount",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Server-calculated values and verification data",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("full", "Full Payment (100%)"),
                    ("partial", "Partial Payment (50%)"),
                    ("remaining", "Remaining Payment (50%)"),
                    ("refund", "Refund"),
                ],
                default="partial",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                    ("partially_refunded", "Partially Refunded"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe customer ID for this transaction only (not stored on user model)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_type", "status"], name="payments_pa_payment_05904b_idx"
            ),
        ),
    ]
