# Generated by Django 5.2.4 on 2025-08-12 03:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image file (JPG, PNG, GIF, BMP, WebP, TIFF, SVG). Maximum size: 5MB.",
                null=True,
                upload_to="profile_pics/",
                validators=[
                    accounts.models.validate_image_file_extension,
                    accounts.models.validate_file_size,
                ],
            ),
        ),
    ]
