# Generated by Django 5.2 on 2025-07-13 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("currency_symbol", models.CharField(default="$", max_length=5)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("country_code", models.CharField(db_index=True, max_length=2)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "default_tax_rate",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
                ),
                ("business_start_time", models.TimeField(default="09:00:00")),
                ("business_end_time", models.TimeField(default="18:00:00")),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("support_phone", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["code", "is_active"], name="regions_reg_code_79fd27_idx"
                    ),
                    models.Index(
                        fields=["country_code", "is_active"],
                        name="regions_reg_country_c3ac5c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegionalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField()),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="regions.region",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["region", "key"], name="regions_reg_region__7dbf9f_idx"
                    )
                ],
                "unique_together": {("region", "key")},
            },
        ),
    ]
