# Generated by Django 5.2.4 on 2025-08-01 10:38

import bookings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_total_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingPicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture_type",
                    models.CharField(
                        choices=[("before", "Before"), ("after", "After")],
                        db_index=True,
                        help_text="Type of picture: before or after service",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload image file (JPEG, PNG, WebP, max 10MB)",
                        upload_to=bookings.models.booking_picture_upload_path,
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Optional caption for the picture",
                        max_length=255,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="bookings.booking",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="Admin user who uploaded this picture",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_booking_pictures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["picture_type", "uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["booking", "picture_type"],
                        name="bookings_bo_booking_15076d_idx",
                    ),
                    models.Index(
                        fields=["uploaded_by", "uploaded_at"],
                        name="bookings_bo_uploade_2ea6cc_idx",
                    ),
                    models.Index(
                        fields=["picture_type", "uploaded_at"],
                        name="bookings_bo_picture_9692f1_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booking", "picture_type", "image"),
                        name="unique_booking_picture_per_type",
                    )
                ],
            },
        ),
    ]
